---
- name: Create a security policy on Palo Alto Firewall
  hosts: localhost
  gather_facts: no
  collections:
    - paloaltonetworks.panos

  vars:
    ip_address: "192.168.29.55"
    username: "admin"
    password: "P@ssw0rd"
    rule_name: "AllowSSH"
    source_zone: "any"
    destination_zone: "any"
    source_ips: "any"
    destination_ips: "any"
    applications: "ssh"
    service: "application-default"
    rule_action: "allow"
    log_end: true

    provider:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - name: Create security policy rule
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        rule_name: "{{ rule_name }}"
        source_zone: "{{ source_zone }}"
        destination_zone: "{{ destination_zone }}"
        source_ip: "{{ source_ips }}"
        destination_ip: "{{ destination_ips }}"
        application: "{{ applications }}"
        service: "{{ service }}"
        action: "{{ rule_action }}"
        log_end: "{{ log_end }}"
        commit: true
      register: create_rule_result

    - name: Show result of rule creation
      debug:
        var: create_rule_result
  connection: local
